---
title: "p8105_hw5_lk2776"
output: html_document
date: "2024-11-05"
---

#Problem 2 

```{r}
library(tidyverse)
library(purrr)
library(broom)
```

```{r}
#function
sim_mean_sd = function(n =30, mu, sigma = 5) {
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma)
)
  
  t_test_out <- t.test(sim_data$x, mu = 0) #null 
  
  tidy(t_test_out)|>
    select(estimate, p.value) 
}

#Run function on data u = 0
sim_results_df =
  expand_grid(
    mu_given = 0,
    iter = 1:5000
  ) |>
  mutate(
    estimate_df = map(mu_given, \(x) sim_mean_sd(mu = x))
  ) |>
  unnest(estimate_df)
```


```{r}
#Run function on data 
sim_results_df_b =
  expand_grid(
    #sample_size = 30,
    mu_given = c(1,2,3,4,5,6),
    iter = 1:5000
  ) |>
  mutate(
    estimate_df = map(mu_given, \(x) sim_mean_sd(mu = x))
  ) |>
  unnest(estimate_df)
sim_results_df_all <- bind_rows(sim_results_df,sim_results_df_b)
```

As shown in the plot below, as true mu increases, the power of the test increased and reached 1. 
effect size is defined as the difference between sample mean  and hypothesized mean(mu = 0). Therefore, as true mean increases, the effect size increases, the power of the test also increases and test is more likely to correctly reject the null hypothesis. 

```{r}
new_df = sim_results_df_all |>
  mutate(reject_null = p.value < 0.05) |>
  group_by(mu_given) |>
  summarise(power_calc = mean(reject_null)) #power for each value of mu # proportion of times the null was rejected. 
  
ggplot(new_df,aes(x = mu_given, y = power_calc)) +
  geom_point() +
  geom_line() +
  labs(
    title = "power against true value of mu",
    x = "true mu",
    y = "power"
  )
```


```{r}
new_df_b = sim_results_df_b |>
  group_by(mu_given) |>
  summarize(
    avg_mu_hat = mean(estimate),
    avg_mu_hat_rejected = mean(estimate[p.value <0.05]))

ggplot(new_df_b, aes(x = mu_given))+
  geom_line(aes(y=avg_mu_hat),color="blue", size = 1) +
  geom_line(aes(y=avg_mu_hat_rejected), color="orange", size =1)+
  labs(
    title = "average mu-hat vs true mu",
    x = "true mu",
    y = "average mu-hat", 
  ) +
  annotate("text", x = 4.7, y = 2, label = "samples with rejected null", color = "orange") +
  annotate("text", x = 4.9, y = 2.25, label = "all samples", color = "blue")

```

