---
title: "problem3"
output: html_document
date: "2024-11-15"
---

```{r}
library(tidyverse)
library(purrr)
library(broom)
```


```{r}
#read data
data = read_csv("./data/homicide-data.csv") |>
  janitor::clean_names() |>
  drop_na() |>
  mutate(city_state = paste(city, state, sep="_"), 
         not_solved = if_else(
           disposition %in% c("Closed without arrest", "Open/No arrest"), 1, 0))  # if match, add 1, otherwise, add 0. 
```

```{r}
summary_data = data |>
  group_by(city_state) |>
  summarize(
    total_number_of_homicides = n(), #count
    unsolved_homicides = sum(not_solved) 
  ) #|>
  #knitr::kable()
```

```{r}
summary_data_balti = summary_data |>
  filter(city_state == "Baltimore_MD") 
  
prop_test_out <- prop.test(summary_data_balti$unsolved_homicides, summary_data_balti$total_number_of_homicides) 

tidy(prop_test_out) |> 
  select(estimate,conf.low,conf.high) 

 # mutate(est_prop = estimate[1], 
  #       low_conf = conf.low[1],
   #      high_conf = conf.high[1]) 
```

```{r}


prop_results_all_cities = summary_data |>
  mutate(prop_test_out_all = map2(unsolved_homicides,total_number_of_homicides, \(x,y) prop.test(x,y))) |>
  #unnest(prop_test_out_all) 
  mutate(tidy_df = map(prop_test_out_all,tidy)) |>
  unnest(tidy_df) |>
  select(city_state,estimate,conf.low,conf.high)
  
  
  
  
  #tidy()
  #unnest()
  

```


```{r}
prop_results_all_cities |>
 mutate(city_state = fct_reorder(city_state,estimate)) |>
  ggplot(aes(x = city_state, y = estimate)) + 
  geom_point(color="purple") +
  geom_errorbar(aes(ymin=conf.low, ymax = conf.high), color = "orange") +
  coord_flip() + #to facilitate the viewing - otherwise - x-axis crowded
  labs(
    title = "proportion of unsolved homicides",
    x = "estimate",
    y = "city and state", 
  )
  
```



```{r}
listcol_df = summary_data |>
  tibble(
    city_state = city_state,
    homi = list_norms
  )

list_norms =
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )

output = map(list_norms, mean_and_sd)

output = map2(input_1, input_2, \(x,y) func(arg_1 =
x, arg_2 = y))


listcol_df =
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )

map(listcol_df$samp, mean_and_sd)

listcol_df =
  listcol_df |>
  mutate(summary = map(samp, mean_and_sd))
listcol_df
```

